### ISSUE TITLE
Tracking with megapose tutorial - ModuleNotFoundError

### ISSUE THREAD

**Issue by mattratcliffe** [lagadic/visp#1204]
Hi there

I have been running through the Tracking with MegaPose tutorial : https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-tracking-megapose.html#megapose_cpp_install

I have successfully installed megapose and activated the environment however when I used the command (as per the tutorial)

`$ python -m megapose_server.run -h`

I get the following error:
 
```
(megapose) C:\visp-ws\visp\script>python -m megapose_server.run -h
Loaded megapose variables {'megapose_dir': './megapose6d', 'megapose_data_dir': './megapose6d/data', 'environment': 'megapose'}
Traceback (most recent call last):
  File "C:\Users\user_1\anaconda3\envs\megapose\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user_1\anaconda3\envs\megapose\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\visp-ws\visp\script\megapose_server\run.py", line 37, in <module>
    from megapose.datasets.object_dataset import RigidObject, RigidObjectDataset
ModuleNotFoundError: No module named 'megapose'
```

Running on Windows 11 Build 22621.1992

Any help much appreciated

cheers
Matt

**Comment by mattratcliffe** [comment]
Hi @SamFlt 

Many thanks for the fast response. 

I deleted my environment , reinstalled via the new install.py script and then run. It seems to at first glance to have executed successfully, here is my output:

```
(megapose) C:\visp-ws\visp\script\megapose_server>python -m megapose_server.run -h
Loaded megapose variables {'megapose_dir': './megapose6d', 'megapose_data_dir': './megapose6d/data', 'environment': 'megapose'}
MKL_NUM_THREADS: 1
OMP_NUM_THREADS: 1
CUDA_VISIBLE_DEVICES: 0
EGL_VISIBLE_DEVICES: 0
usage: run.py [-h] [--host HOST] [--port PORT] [--model {RGB,RGBD,RGB-multi-hypothesis,RGBD-multi-hypothesis}]
              [--meshes-directory MESHES_DIRECTORY] [--optimize] [--num-workers NUM_WORKERS]

optional arguments:
  -h, --help            show this help message and exit
  --host HOST           IP or hostname to bind the server to. Set to 0.0.0.0 if you wish to listen for incoming
                        connections from any source (dangerous)
  --port PORT           The port on which to listen for new connections
  --model {RGB,RGBD,RGB-multi-hypothesis,RGBD-multi-hypothesis}
                        Which MegaPose model to use. Some models require the depth map. Some models generate multiple
                        hypotheses when estimating the pose, at the cost of more computation. Options: RGB, RGBD, RGB-
                        multi-hypothesis, RGBD-multi-hypothesis
  --meshes-directory MESHES_DIRECTORY
                        Directory containing the 3D models. each 3D model must be in its own subfolder
  --optimize            Experimental: Optimize network for inference speed. This may incur a loss of accuracy.
  --num-workers NUM_WORKERS
                        Number of workers for rendering
```

I'll continue running through the tutorial.

Thanks for the support!
Matt
